---
# Name your file secrets.yml
# no token we needed for this project so far

development:
  DB_FILENAME: db/local/dev.db
  service : s3
  access_key_id : 'access_key_id'
  secret_key_id : 'secret_key_id'
  region : 'ap-northeast-2'
  bucket : 'bucket' 

test:
  DB_FILENAME: db/local/test.db
  service : s3
  access_key_id : 'access_key_id'
  secret_key_id : 'secret_key_id'
  region : 'ap-northeast-2'
  bucket : 'bucket'  
production:
